/* A disposable DB proves migration preservation and real authenticated submission/approval behavior. */
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text,email_confirmed_at timestamptz,created_at timestamptz default now(),deleted_at timestamptz,is_anonymous boolean default false);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 const root=path.resolve(__dirname,'../..'),migration='20261005111439_studio_blocks.sql',dir=path.join(root,'supabase/migrations');
 for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.sql')&&f<migration).sort())await db.exec(fs.readFileSync(path.join(dir,f),'utf8'));
 const user='11111111-1111-4111-8111-111111111111';
 await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,'test@example.test',now(),'{\"display_name\":\"Studio test\"}')",[user]);
 await db.query("insert into workspace_members(user_id,role,active) values($1,'admin',true)",[user]);
 const owner=async(sql,args=[])=>{await db.exec('reset role');return (await db.query(sql,args)).rows;};
 const as=async(sql,args=[])=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');return(await db.query(sql,args)).rows;};
 const source=(await owner("select slots from workspace_content_sources where course='common' and chapter='c2' and locale='en'"))[0].slots;
 const submit=async(slots,base=source,release=null)=>(await as("select workspace_submit_localized_content($1,'common','c2',$2,$3,$4,now(),'C2 editing test','en',null) id",[crypto.randomUUID(),slots,base,release]))[0].id;
 const old=structuredClone(source),heading=Object.keys(old)[0],field=Object.keys(old[heading])[0];old[heading][field]+=' edited';
 const pending=await submit(old);
 const snapshot=async()=>JSON.stringify(await owner('select to_jsonb(s) row from workspace_submissions s order by id'));
 const before=await snapshot(),sourceBefore=JSON.stringify(await owner('select to_jsonb(s) row from workspace_content_sources s order by course,chapter,locale'));
 const sql=fs.readFileSync(path.join(dir,migration),'utf8');assert.equal(sql,fs.readFileSync(path.join(root,'supabase/STUDIO_BLOCKS_SETUP.sql'),'utf8'));await db.exec(sql);
 assert.equal(await snapshot(),before,'pending ID, payload, timestamp, author, status and revision are unchanged');
 assert.equal(JSON.stringify(await owner('select to_jsonb(s) row from workspace_content_sources s order by course,chapter,locale')),sourceBefore,'source labels never change');
 await as("select workspace_decide_content($1,1,'approved','Old pending still approves')",[pending]);
 const base=(await owner("select slots from workspace_beta_content where course='common' and chapter='c2' and locale='en'"))[0].slots;
 const fresh=structuredClone(base),slot=Object.keys(source).find(k=>JSON.stringify(source[k]).includes('Motor and bodily'));
 fresh._studio={version:1,formats:[],boxes:[{id:'box-'+crypto.randomUUID(),slot,template:'gradient-row',anchor:2,fields:[[{text:'Intersubjective meaning-making: stimulated, not lived'}],[{text:'Human understanding develops with others.',bold:true}]],align:'left',size:16}]};
 const newId=await submit(fresh,base,pending),staleId=await submit(base,base,pending);
 await as("select workspace_decide_content($1,1,'approved','New box approved')",[newId]);
 const stored=(await owner("select slots from workspace_beta_content where course='common' and chapter='c2' and locale='en'"))[0].slots;
 assert.deepEqual(stored._studio,fresh._studio);
 await assert.rejects(()=>as("select workspace_decide_content($1,1,'approved','Must not erase new box')",[staleId]),/newer version/);
 assert.equal((await owner('select status from workspace_submissions where id=$1',[staleId]))[0].status,'pending');
 const bad=structuredClone(fresh);bad._studio.boxes[0].fields[0][0].color='red;position:fixed';
 assert.equal((await owner('select workspace_valid_content($1,$2) ok',[bad,base]))[0].ok,false);
 await db.exec(sql);assert.deepEqual((await owner("select slots from workspace_beta_content where course='common' and chapter='c2' and locale='en'"))[0].slots,stored,'setup can be re-run without touching content');
 const course=(await owner("select slots from workspace_content_sources where course='psychology' and chapter='c2' and locale='en'"))[0].slots;const added=structuredClone(course);added['c2.examples'].push({title:'New',thinking:'',typing:'',processing:''});assert.equal((await owner('select workspace_valid_content($1,$2) ok',[added,course]))[0].ok,true);
 console.log('PASS studio_blocks: pending unchanged, legacy approval, new submission, stale approval guard, validation and idempotent setup');await db.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
