/* Disposable Postgres fixture. Never changes live accounts, roles or content. */
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text,email_confirmed_at timestamptz,created_at timestamptz default now(),deleted_at timestamptz,is_anonymous boolean default false);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 for(const f of fs.readdirSync(path.join(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8'));
 const ids=Array.from({length:6},(_,n)=>`${n+1}1111111-1111-4111-8111-111111111111`);
 const [admin,second,member,pending,unconfirmed,inactive]=ids;
 for(const [i,id] of ids.entries())await db.query('insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,$3,$4)',[id,`person${i}@example.test`,id===unconfirmed?null:'2026-09-30',JSON.stringify({display_name:'Person '+i,role:'admin'})]);
 await db.query("insert into workspace_members(user_id,role,active) values($1,'admin',true),($2,'admin',true),($3,'member',true),($4,'admin',false)",[admin,second,member,inactive]);
 async function as(user,sql,args=[]){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await db.exec('set role '+(user?'authenticated':'anon'));return db.query(sql,args);}
 const deny=async(user,sql,args=[],pattern)=>assert.rejects(()=>as(user,sql,args),pattern);
 const list='select workspace_list_team($1,$2,$3) result',set='select workspace_set_team_access($1,$2,$3,$4) result';
 for(const user of [null,member,pending,inactive]){
  await deny(user,list,['',0,50]);await deny(user,set,[pending,'admin',true,0]);
 }
 await deny(member,'select aiwise_private.set_team_access($1,$2,$3,$4)',[member,'admin',true,1]);
 await deny(member,'select * from auth.users');
 const people=(await as(admin,list,['',0,50])).rows[0].result;
 assert.equal(people.total,6);assert.equal(people.members.find(p=>p.user_id===pending).version,0);
 assert.equal(people.members.find(p=>p.user_id===unconfirmed).confirmed,false);
 assert.equal((await as(admin,list,['person2',0,50])).rows[0].result.total,1);
 assert.equal((await as(admin,list,['%',0,50])).rows[0].result.total,0,'search treats wildcard as literal');
 assert.equal((await as(admin,list,['',0,2])).rows[0].result.members.length,2);
 await deny(admin,list,['',-1,50]);await deny(admin,list,['',0,101]);
 await deny(admin,set,[unconfirmed,'member',true,0],/confirm their email/);
 await deny(admin,set,[pending,'owner',true,0]);
 await deny(admin,set,[pending,'member',null,0]);
 const approved=(await as(admin,set,[pending,'member',true,0])).rows[0].result;
 assert.equal(approved.version,1);assert.equal(approved.active,true);
 await deny(second,set,[pending,'admin',true,0],/access changed/);
 const promoted=(await as(admin,set,[member,'admin',true,1])).rows[0].result;
 assert.equal(promoted.version,2);assert.equal((await as(member,'select workspace_role() r')).rows[0].r,'admin');
 assert.equal((await as(member,list,['',0,50])).rows[0].result.total,6);
 await as(admin,set,[member,'member',true,2]);
 await deny(member,list,['',0,50]);
 await deny(member,"update workspace_members set role='admin' where user_id=$1",[member]);
 await deny(member,"insert into workspace_members(user_id,role) values($1,'admin')",[unconfirmed]);
 await deny(member,'delete from workspace_members where user_id=$1',[admin]);
 await deny(admin,'select * from aiwise_private.team_access_log');
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from aiwise_private.team_access_log')).rows[0].n,3);
 const baseline=(await db.query("select slots from workspace_content_sources where course='common' and chapter='c1' and locale='en'")).rows[0].slots;
 const submit='select workspace_submit_localized_content($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) id';
 const params=['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','common','c1',baseline,baseline,null,'2026-09-30','Admin draft','en',null];
 for(const user of [null,member,pending,inactive])await deny(user,submit,params);
 await deny(member,'select workspace_submit_content($1,$2,$3,$4,$5,$6,$7,$8)',params.slice(0,8));
 await deny(member,'select aiwise_private.submit_localized_content($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',params);
 const submission=(await as(admin,submit,params)).rows[0].id;
 assert.equal((await as(member,'select count(*)::int n from workspace_submissions')).rows[0].n,0);
 assert.equal((await as(admin,'select count(*)::int n from workspace_submissions')).rows[0].n,1);
 await deny(member,'select workspace_decide_content($1,1,$2,$3)',[submission,'approved','No']);
 await as(admin,'select workspace_decide_content($1,1,$2,$3)',[submission,'approved','Reviewed']);
 assert.equal((await as(member,'select count(*)::int n from workspace_beta_content')).rows[0].n,1);
 const anchor={kind:'comment',path:'body>main:nth-of-type(1)>p:nth-of-type(1)',fingerprint:'a'.repeat(64),excerpt:'Content'};
 const memo='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 await as(member,'insert into workspace_beta_memos(id,page,anchor,body) values($1,$2,$3,$4)',[memo,'common/aiwise-c1-final.html?course=aws1',anchor,'Member comment']);
 await as(pending,'insert into workspace_beta_replies(id,memo_id,body) values(gen_random_uuid(),$1,$2)',[memo,'Member reply']);
 assert.equal((await as(member,'update workspace_beta_memos set resolved=true where id=$1 returning id',[memo])).rows.length,0,'even author cannot resolve');
 assert.equal((await as(admin,'update workspace_beta_memos set resolved=true where id=$1 returning id',[memo])).rows.length,1);
 assert.equal((await as(member,'select count(*)::int n from workspace_beta_replies')).rows[0].n,1);
 await as(admin,set,[member,'member',false,3]);
 assert.equal((await as(member,'select count(*)::int n from workspace_beta_memos')).rows[0].n,0);
 await deny(member,'insert into workspace_beta_replies(id,memo_id,body) values(gen_random_uuid(),$1,$2)',[memo,'Revoked']);
 await as(admin,set,[second,'member',true,1]);
 await deny(second,set,[admin,'member',true,1]);
 await deny(admin,set,[admin,'member',true,1],/at least one active administrator/);
 await deny(admin,set,[admin,'admin',false,1],/at least one active administrator/);
 await as(admin,set,[second,'admin',true,2]);
 await as(admin,set,[admin,'member',true,1]);
 await deny(admin,list,['',0,50]);
 assert.equal((await as(second,list,['',0,50])).rows[0].result.members.find(p=>p.user_id===second).role,'admin');
 console.log('PASS team access: admin-only directory and mutations, pending/confirmed accounts, literal search and pagination, stale versions, audit privacy, last-admin protection, delegation and revocation, member submission/approval denial, Beta feedback allowed, admin-only resolution.');
 await db.close();
})().catch(error=>{console.error(error);process.exit(1)});
