/* Full migration chain against disposable PostgreSQL; never enrolls real users. */
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{randomUUID,randomBytes}=require('node:crypto');
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text,email_confirmed_at timestamptz,created_at timestamptz default now(),deleted_at timestamptz,is_anonymous boolean default false);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
const root=path.resolve(__dirname,'../..');for(const f of fs.readdirSync(path.join(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8'));
const admin=randomUUID(),otherAdmin=randomUUID(),member=randomUUID(),newcomer=randomUUID(),wrong=randomUUID(),unconfirmed=randomUUID(),paused=randomUUID(),later=randomUUID();
for(const [id,email,confirmed] of [[admin,'admin@eur.nl',true],[otherAdmin,'admin2@eur.nl',true],[member,'member@eur.nl',true],[newcomer,'new@eur.nl',true],[wrong,'outsider@example.test',true],[unconfirmed,'pending@eur.nl',false],[paused,'paused@eur.nl',true],[later,'later@eur.nl',true]])await db.query('insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,case when $3 then now() end,$4)',[id,email,confirmed,{role:'admin'}]);
await db.query("insert into workspace_members(user_id,role,active) values($1,'admin',true),($2,'admin',true),($3,'member',true),($4,'member',false)",[admin,otherAdmin,member,paused]);
async function as(user,sql,args=[]){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await db.exec('set role '+(user?'authenticated':'anon'));return (await db.query(sql,args)).rows;}
const create='select workspace_create_invitation($1,$2,$3,$4,$5,$6,$7,$8) id',details='select workspace_invitation_details($1,$2) value',accept='select workspace_accept_invitation($1,$2) value';
const make=(over={})=>Object.assign({id:randomUUID(),token:randomBytes(32).toString('hex'),label:'Reviewers',role:'member',eligibility:'email',target:'new@eur.nl',days:7,max:1},over);const args=i=>[i.id,i.token,i.label,i.role,i.eligibility,i.target,i.days,i.max];const read=async(actor,i)=>(await as(actor,details,[i.id,i.token]))[0].value;
let i=make();for(const actor of [null,member,newcomer,paused])await assert.rejects(()=>as(actor,create,args(i)));
await as(admin,create,args(i));await as(admin,create,args(i));assert.equal((await as(admin,'select workspace_list_invitations() value'))[0].value.total,1);await assert.rejects(()=>as(otherAdmin,create,args(i)));await assert.rejects(()=>as(admin,create,args({...i,role:'admin'})));
const listed=(await as(admin,'select workspace_list_invitations() value'))[0].value.invitations[0];assert.equal(listed.token,undefined);assert.equal(listed.token_hash,undefined);
for(const actor of [null,member,newcomer])await assert.rejects(()=>as(actor,'select workspace_list_invitations()'));
for(const actor of [null,unconfirmed])await assert.rejects(()=>as(actor,details,[i.id,i.token]));assert.equal((await read(wrong,i)).status,'wrong_email');await assert.rejects(()=>as(wrong,accept,[i.id,i.token]));await assert.rejects(()=>as(newcomer,details,[i.id,'f'.repeat(64)]));
await as(newcomer,accept,[i.id,i.token]);await as(newcomer,accept,[i.id,i.token]);assert.equal((await as(newcomer,'select role from workspace_members where user_id=$1',[newcomer]))[0].role,'member');assert.equal((await read(newcomer,i)).status,'accepted');assert.equal((await as(admin,'select workspace_list_invitations() value'))[0].value.invitations[0].uses,1);
await as(admin,'select workspace_revoke_invitation($1)',[i.id]);assert.equal((await read(newcomer,i)).status,'accepted','revoking a link does not revoke existing access');
const adminInvite=make({role:'admin',target:'new@eur.nl'});for(const bad of [{eligibility:'any',target:''},{eligibility:'domain',target:'eur.nl'},{max:2}])await assert.rejects(()=>as(admin,create,args({...adminInvite,...bad})));
await as(admin,create,args(adminInvite));await as(newcomer,accept,[adminInvite.id,adminInvite.token]);assert.equal((await as(newcomer,'select workspace_role() role'))[0].role,'admin');
const keep=make({target:'new@eur.nl'});await as(admin,create,args(keep));await as(newcomer,accept,[keep.id,keep.token]);assert.equal((await as(newcomer,'select workspace_role() role'))[0].role,'admin','member invitation never downgrades an administrator');
const domain=make({eligibility:'domain',target:'eur.nl',max:2});await as(admin,create,args(domain));assert.equal((await read(wrong,domain)).status,'wrong_domain');assert.equal((await read(paused,domain)).status,'paused');await assert.rejects(()=>as(paused,accept,[domain.id,domain.token]));await as(member,accept,[domain.id,domain.token]);await as(later,accept,[domain.id,domain.token]);assert.equal((await read(otherAdmin,domain)).status,'used');await assert.rejects(()=>as(otherAdmin,accept,[domain.id,domain.token]));
const revoked=make({eligibility:'any',target:'',max:5});await as(admin,create,args(revoked));await as(otherAdmin,'select workspace_revoke_invitation($1)',[revoked.id]);assert.equal((await read(wrong,revoked)).status,'revoked');await assert.rejects(()=>as(wrong,accept,[revoked.id,revoked.token]));
const expired=make({eligibility:'any',target:''});await as(admin,create,args(expired));await db.exec('reset role');await db.query("update aiwise_private.team_invitations set expires_at=now()-interval '1 second' where id=$1",[expired.id]);assert.equal((await read(wrong,expired)).status,'expired');
const issuer=make({eligibility:'any',target:''});await as(admin,create,args(issuer));await db.exec('reset role');await db.query("update workspace_members set role='member' where user_id=$1",[admin]);assert.equal((await read(wrong,issuer)).status,'issuer_inactive');await assert.rejects(()=>as(wrong,accept,[issuer.id,issuer.token]));
for(const actor of [member,newcomer]){await assert.rejects(()=>as(actor,'select * from aiwise_private.team_invitations'));await assert.rejects(()=>as(actor,'select * from aiwise_private.team_invitation_acceptances'));await assert.rejects(()=>as(actor,"update workspace_members set role='admin' where user_id=$1",[actor]));}
await db.exec('reset role');const log=(await db.query('select * from aiwise_private.team_access_log where user_id=$1 order by id',[newcomer])).rows;assert.equal(log[0].actor_id,admin);assert.equal(log[0].new_role,'member');assert.equal(log[1].new_role,'admin');
const guards=(await db.query("select n.nspname,p.prosecdef,has_function_privilege('anon',p.oid,'execute') anon from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('workspace_create_invitation','workspace_list_invitations','workspace_revoke_invitation','workspace_invitation_details','workspace_accept_invitation')")).rows;assert.equal(guards.length,5);assert(guards.every(g=>!g.anon&&!g.prosecdef));
console.log('PASS invitations: confirmed identity, administrator-only creation/list/revocation, named admin grants, exact email/domain, expiry/use limits, idempotent accept/create, paused account and issuer revocation, no downgrade, private token hashes and audit attribution.');await db.close();})().catch(e=>{console.error(e.message,e.stack);process.exitCode=1;});
