/* Full migration chain against disposable PostgreSQL; never enrolls real users. */
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{randomUUID,randomBytes}=require('node:crypto');
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text,email_confirmed_at timestamptz,created_at timestamptz default now(),deleted_at timestamptz,is_anonymous boolean default false);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
const root=path.resolve(__dirname,'../..');for(const f of fs.readdirSync(path.join(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8'));
const admin=randomUUID(),member=randomUUID(),newcomer=randomUUID(),paused=randomUUID(),unconfirmed=randomUUID();
for(const [id,email,confirmed] of [[admin,'admin@eur.nl',true],[member,'member@eur.nl',true],[newcomer,'new@outside.test',true],[paused,'paused@eur.nl',true],[unconfirmed,'pending@eur.nl',false]])await db.query('insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,case when $3 then now() end,$4)',[id,email,confirmed,{role:'admin'}]);
await db.query("insert into workspace_members(user_id,role,active) values($1,'admin',true),($2,'member',true),($3,'member',false)",[admin,member,paused]);
async function as(user,sql,args=[]){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await db.exec('set role '+(user?'authenticated':'anon'));return (await db.query(sql,args)).rows;}
const create='select workspace_create_join_link($1,$2,$3) id',details='select workspace_invitation_details($1,$2) value',request='select workspace_request_team_access($1,$2) value';
const make=()=>({id:randomUUID(),token:randomBytes(32).toString('hex'),label:'Team link'}),args=i=>[i.id,i.token,i.label],read=async(u,i)=>(await as(u,details,[i.id,i.token]))[0].value;
const link=make();for(const user of [null,member,newcomer,paused])await assert.rejects(()=>as(user,create,args(link)));
await as(admin,create,args(link));await as(admin,create,args(link));await assert.rejects(()=>as(admin,create,[link.id,link.token,'Changed']));
await db.exec('reset role');const stored=(await db.query('select * from aiwise_private.team_invitations where id=$1',[link.id])).rows[0];assert.equal(stored.role,'member');assert.equal(stored.eligibility,'any');assert.equal(stored.max_uses,null);assert.equal(new Date(stored.expires_at)-new Date(stored.created_at),7*86400000);
for(const user of [null,member,newcomer])await assert.rejects(()=>as(user,'select workspace_list_invitations()'));
for(const user of [null,unconfirmed])await assert.rejects(()=>as(user,request,[link.id,link.token]));await assert.rejects(()=>as(newcomer,request,[link.id,'f'.repeat(64)]));assert.equal((await read(newcomer,link)).approval_required,true);
for(const user of [admin,member,newcomer]){await assert.rejects(()=>as(user,'select workspace_accept_invitation($1,$2)',[link.id,link.token]));await assert.rejects(()=>as(user,'select aiwise_private.accept_invitation($1,$2)',[link.id,link.token]));await assert.rejects(()=>as(user,'select workspace_create_invitation($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),link.token,'Old UI','admin','email','x@eur.nl',30,1]));}
await as(newcomer,request,[link.id,link.token]);await as(newcomer,request,[link.id,link.token]);assert.equal((await read(newcomer,link)).status,'requested');assert.equal((await as(newcomer,'select workspace_role() role'))[0].role,null,'request grants no access despite metadata role');
let list=(await as(admin,'select workspace_list_team() result'))[0].result;assert.equal(list.pending_requests,1);assert.equal(list.members[0].user_id,newcomer);assert.equal(list.members[0].role,'member');assert.equal(list.members[0].access,'pending');assert(list.members[0].requested_at);
await assert.rejects(()=>as(newcomer,'select workspace_set_team_access($1,$2,$3,$4)',[newcomer,'admin',true,0]));
await as(admin,'select workspace_set_team_access($1,$2,$3,$4)',[newcomer,'member',true,0]);assert.equal((await read(newcomer,link)).status,'member');assert.equal((await read(newcomer,link)).current_role,'member');assert.equal((await as(admin,'select workspace_list_team() result'))[0].result.pending_requests,0);
await as(admin,'select workspace_set_team_access($1,$2,$3,$4)',[newcomer,'admin',true,1]);await as(newcomer,request,[link.id,link.token]);assert.equal((await read(newcomer,link)).current_role,'admin','link never downgrades existing access');
await assert.rejects(()=>as(paused,request,[link.id,link.token]));assert.equal((await read(paused,link)).status,'paused');
// More than the old 50-person maximum: no enrollment and one request per account.
const people=[];for(let n=0;n<55;n++){const id=randomUUID();people.push(id);await db.exec('reset role');await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())",[id,'person'+n+'@any-domain.test']);await as(id,request,[link.id,link.token]);}
assert.equal((await as(admin,'select workspace_list_invitations() result'))[0].result.invitations[0].requests,56);
await as(admin,'select workspace_set_team_access($1,$2,$3,$4)',[people[0],'member',false,0]);await assert.rejects(()=>as(people[0],request,[link.id,link.token]),'declined account cannot re-request through a link');
const fresh=make();await as(admin,create,args(fresh));await as(people[1],request,[fresh.id,fresh.token]);assert.equal((await as(admin,'select workspace_list_team() result'))[0].result.pending_requests,54,'another link does not duplicate a pending request');
await as(admin,'select workspace_revoke_invitation($1)',[link.id]);assert.equal((await read(people[1],link)).status,'requested','revocation keeps submitted requests');
const outsider=randomUUID();await db.exec('reset role');await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'later@any.test',now())",[outsider]);await assert.rejects(()=>as(outsider,request,[link.id,link.token]));
await db.exec('reset role');await db.query("update aiwise_private.team_invitations set expires_at=now()-interval '1 second' where id=$1",[fresh.id]);await assert.rejects(()=>as(outsider,request,[fresh.id,fresh.token]));
const demoted=make();await as(admin,create,args(demoted));await as(newcomer,'select workspace_set_team_access($1,$2,$3,$4)',[admin,'member',true,1]);await assert.rejects(()=>as(outsider,request,[demoted.id,demoted.token]));
for(const user of [member,newcomer,outsider]){await assert.rejects(()=>as(user,'select * from aiwise_private.team_join_requests'));await assert.rejects(()=>as(user,'select * from aiwise_private.team_invitations'));}
await db.exec('reset role');const guards=(await db.query("select p.prosecdef,has_function_privilege('anon',p.oid,'execute') anon from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('workspace_create_join_link','workspace_request_team_access')")).rows;assert.equal(guards.length,2);assert(guards.every(g=>!g.prosecdef&&!g.anon));
console.log('PASS join invitations: fixed 7 days, unlimited confirmed recipients, private idempotent requests, no automatic enrollment, administrator approval and later delegation, declined/paused protection, expired/revoked links, issuer revocation, retired legacy endpoints.');await db.close();
})().catch(e=>{console.error(e.message,e.stack);process.exitCode=1;});
