const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom'),settle=()=>new Promise(r=>setTimeout(r,0));
const version='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
function fixture(options={}){const {document,window:dom}=parseHTML('<html><body><div id="list"></div></body></html>');Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._value||this.querySelector('option')?.value;},set(v){this._value=v;}});let state={status:'member',user:{id:'one'}};const calls=[];
 const data={fingerprint:'current-copy',previous_number:1,previous_title:'First',open_memos:2,changes:[{course:'common',chapter:'c1',locale:'en',key:'c1.a',kind:'changed',before:'Old',after:'<script>New</script>'},{course:'ped',chapter:'c2',locale:'nl',key:'c2.examples',kind:'added',after:['Example']}],checks:[{version_id:version,course:'common',chapter:'c1',locale:'en',item_key:'c1.a',reviewed:true,updated_at:'2026-10-01',reviewer_name:'Reviewer'}]};
 const window={AIWiseAuth:{snapshot:()=>state},AIWiseBackend:{getClient:async()=>({rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>{if(options.pending)await options.pending;return options.error?{error:options.error}:{data:structuredClone(data)};}};}})}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../beta-checklist.js'),'utf8'),{window,document,URLSearchParams,AbortController,setTimeout,clearTimeout});const api=window.AIWiseBetaChecklist,dispose=api.mount(document.querySelector('#list'),options.current?null:version);return {document,api,calls,data,dispose,auth:s=>state=s};}
test('pending changes come first and reviewed content is safely rendered when requested',async()=>{const f=fixture();await settle();assert.equal(f.document.querySelectorAll('.beta-change-row').length,1);assert.match(f.document.querySelector('[data-check-summary]').textContent,/1 of 2 changes reviewed · 2 open memos/);const filter=f.document.querySelector('select');filter.value='all';filter.onchange();assert.equal(f.document.querySelectorAll('.beta-change-row').length,2);assert.match(f.document.querySelector('.beta-change-row').textContent,/Example/);assert.equal(f.document.querySelector('script'),null);f.dispose();});
test('review writes exact version, scope, language and expected previous state',async()=>{const f=fixture();await settle();f.document.querySelector('[data-check-item]').click();await settle();const call=f.calls.find(c=>c.name==='workspace_check_beta_item');assert.equal(call.args.p_version,version);assert.equal(call.args.p_course,'ped');assert.equal(call.args.p_locale,'nl');assert.equal(call.args.p_expected,null);f.dispose();});
test('live Beta supports fingerprint-checked review and navigation preserves language, course and item',async()=>{const f=fixture({current:true});await settle();f.document.querySelector('[data-check-item]').click();await settle();const write=f.calls.find(c=>c.name==='workspace_check_beta_draft_item');assert.equal(write.args.p_fingerprint,'current-copy');assert.equal(write.args.p_version,undefined);const link=f.api.previewLink(version,{course:'ped',chapter:'map',locale:'nl',key:'map.node-1'});const p=new URLSearchParams(link.split('?')[1]);assert.match(p.get('page'),/aiwise-c1-anatomy-2d.html\?course=ped&lang=nl/);assert.equal(p.get('item'),'map.node-1');f.dispose();});
test('missing setup and account changes never present a successful review',async()=>{const f=fixture({error:{code:'PGRST202'}});await settle();assert.match(f.document.querySelector('[data-check-summary]').textContent,/unavailable/);assert.equal(f.document.querySelector('[data-check-item]'),null);f.dispose();let finish;const pending=new Promise(r=>finish=r),g=fixture({pending});await settle();g.auth({status:'signed-out'});finish();await settle();assert.equal(g.document.querySelector('[data-check-item]'),null);g.dispose();});
test('legacy fallback is labelled as a review snapshot without claiming publication or requiring unchanged items',async()=>{const f=fixture({current:true});f.data.previous_kind='snapshot';f.data.changes=[];f.data.checks=[];await settle();assert.match(f.document.querySelector('[data-check-baseline]').textContent,/V1.*review snapshot; not published/);assert.match(f.document.querySelector('[data-check-summary]').textContent,/0 of 0 changes reviewed/);assert.doesNotMatch(f.document.querySelector('[data-check-list]').textContent,/published/);f.dispose();});
