const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom'),settle=()=>new Promise(r=>setTimeout(r,0));
function fixture(options={}){const {document}=parseHTML('<html><body><div id="invitation-content"></div></body></html>');let state=options.signedOut?{status:'signed-out',user:null}:{status:'not-member',user:{id:'new',email:'new@eur.nl'}},listener,calls=[],accepted=false;
const window={AIWiseAuth:{snapshot:()=>state,subscribe:fn=>{listener=fn;fn(state)},refresh:async()=>{state={...state};listener(state)}},AIWiseBackend:{getClient:async()=>({rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>{if(options.pending)await options.pending;if(name==='workspace_request_team_access'){accepted=true;return {data:{requested:true}};}return {data:{label:'Team <review>',role:'member',approval_required:!options.oldAPI,status:accepted?'requested':options.status||'eligible',current_role:options.status==='member'?'member':null,expires_at:'2026-10-08',domain:'eur.nl'}};}};}})}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../invite.js'),'utf8'),{window,document,location:{hash:options.bad?'#bad':'#aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.'+'b'.repeat(64)},AbortController,setTimeout,clearTimeout});return{document,calls,setAuth:s=>{state=s;listener(s)}};}
test('signed-out and malformed invitation pages send no secret to the server',async()=>{for(const options of [{signedOut:true},{bad:true}]){const f=fixture(options);await settle();assert.equal(f.calls.length,0);assert.equal(f.document.querySelector('button'),null);}});
test('invitation is inspected first; requesting explicitly waits for administrator approval',async()=>{const f=fixture();await settle();assert.equal(f.calls.length,1);assert.equal(f.calls[0].name,'workspace_invitation_details');assert.equal(f.document.querySelector('review'),null);await f.document.querySelector('button').onclick();await settle();assert.equal(f.calls.filter(c=>c.name==='workspace_request_team_access').length,1);assert.equal(f.document.querySelector('a').getAttribute('href'),'./');assert.match(f.document.body.textContent,/Request sent.*administrator/);assert.doesNotMatch(f.document.body.textContent,/Open Workspace/);});
test('eligibility failure, expired or paused invitation cannot be accepted',async()=>{for(const status of ['expired','paused','revoked','issuer_inactive']){const f=fixture({status});await settle();assert.equal(f.document.querySelector('button'),null);assert(f.document.querySelector('[role=alert]'));}});
test('late private invitation details cannot appear after sign-out',async()=>{let finish;const pending=new Promise(r=>finish=r),f=fixture({pending});await settle();f.setAuth({status:'signed-out',user:null});finish();await settle();assert.doesNotMatch(f.document.body.textContent,/Team <review>/);assert.equal(f.document.querySelector('button'),null);});

test('old automatic invitation API cannot be used by the request page',async()=>{const f=fixture({oldAPI:true});await settle();assert.equal(f.document.querySelector('button'),null);assert.match(f.document.body.textContent,/not ready/);});
