const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom');
const source=fs.readFileSync(path.join(__dirname,'../my-page.js'),'utf8');
const settle=()=>new Promise(r=>setTimeout(r,0));
function fixture(role='member',handler=async()=>({data:[]})){
 const {document,window:dom}=parseHTML('<html><body><h1 id="room-title">Common Studio</h1></body></html>');
 Object.defineProperty(document,'currentScript',{value:{src:'https://example.test/workspace/my-page.js'}});
 const create=document.createElement.bind(document);document.createElement=(tag)=>{const n=create(tag);if(tag==='dialog'){n.showModal=()=>{n.open=true;};n.close=()=>{n.open=false;};}return n;};
 let state=role?{status:'member',role,user:{id:'owner',displayName:'Test <user>'}}:{status:'signed-out'},listener,accountOpened=0;const store=new Map(),calls=[];let blocked=false;
 const storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('Storage full');store.set(k,v);}};
 const chain=table=>{const filters=[],q={select:()=>q,contains:(k,v)=>{filters.push([k,v]);return q;},eq:(k,v)=>{filters.push([k,v]);return q;},order:()=>q,limit:()=>q,abortSignal:async()=>{calls.push({table,filters});return handler({table,filters});}};return q;};
 const window={AIWiseAuth:{snapshot:()=>state,subscribe:fn=>{listener=fn;fn(state);}},AIWiseBackend:{getClient:async()=>({from:chain})},AIWiseAccount:{open:()=>accountOpened++},AIWiseSidebar:{close:()=>{}},AIWiseMotion:{enter:()=>{},cancel:()=>{}},addEventListener:()=>{}};
 vm.runInNewContext(source,{window,document,location:{href:'https://example.test/workspace/#beta',hash:'#beta',pathname:'/workspace/'},URL,AbortController,setTimeout,clearTimeout,localStorage:storage});
 return {document,api:window.AIWiseMyPage,calls,store,account:()=>accountOpened,setAuth:a=>{state=a;listener(a);},input:(selector,value)=>{const n=document.querySelector(selector);n.value=value;n.dispatchEvent(new dom.Event('input'));},block:()=>blocked=true};
}
test('persistent My page tab sends signed-out users to sign in without private queries',()=>{const c=fixture(null);assert.equal(c.document.querySelector('.mp-tab').textContent,'My page');c.api.open();assert.equal(c.account(),1);assert.equal(c.calls.length,0);});
test('members see fixed sections and only their feedback; no administrator data is requested',async()=>{const c=fixture();c.api.open();await settle();assert.equal(c.document.querySelectorAll('.mp-body>section').length,5);assert.equal(c.calls.some(q=>['workspace_submissions','workspace_beta_versions'].includes(q.table)),false);assert.ok(c.calls.filter(q=>q.table==='workspace_beta_memos').some(q=>q.filters.some(([k,v])=>k==='author_id'&&v==='owner')));assert.equal(c.document.querySelector('.mp-header user'),null);});
test('personal notes are scoped to the account and private contents clear on sign-out',async()=>{const c=fixture();c.api.open();c.input('[data-mp-note]','My private note');assert.equal(JSON.parse(c.store.get('aiwise_my_page_v1:owner:note')),'My private note');c.setAuth({status:'signed-out'});assert.equal(c.document.querySelector('#my-page').textContent,'');c.setAuth({status:'member',role:'member',user:{id:'other'}});c.api.open();assert.equal(c.document.querySelector('[data-mp-note]').value,'');await settle();});
test('a storage failure keeps unsaved notes visible and prevents silently closing the panel',()=>{const c=fixture();c.api.open();c.block();c.input('[data-mp-note]','Keep this');c.document.querySelector('[data-mp-close]').onclick();assert.equal(c.document.querySelector('#my-page').open,true);assert.match(c.document.querySelector('[data-mp-save-status]').textContent,/Could not save/);});
test('late private responses do not reappear after account revocation',async()=>{let release;const pending=new Promise(r=>release=r);const c=fixture('member',async()=>{await pending;return{data:[{id:'memo',page:'common/lobby.html',author_name:'Private name',body:'Secret text',created_at:'2026-10-01'}]};});c.api.open();await settle();c.setAuth({status:'not-member',user:{id:'owner'}});release();await settle();assert.equal(c.document.querySelector('#my-page').textContent,'');});
