const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom');const settle=()=>new Promise(r=>setTimeout(r,0));
function fixture(options={}){
 const dom=parseHTML('<html><body><h1 id="room-title">Beta</h1></body></html>'),{document}=dom;Object.defineProperty(document,'currentScript',{value:{src:'https://example.test/workspace/page-feedback.js'}});
 dom.HTMLElement.prototype.showModal=function(){this.setAttribute('open','');};dom.HTMLElement.prototype.close=function(){this.removeAttribute('open');};Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._value||this.querySelector('option')?.value;},set(v){this._value=v;}});
 let auth=options.signedOut?{status:'signed-out'}:{status:'member',role:options.role||'member',user:{id:'one'}},subscriber,account=0;const calls=[];let failure=options.failure;
 const backend={rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>({data:args.p_id,error:failure?{code:'NETWORK'}:null})};},from:table=>{const q={select:()=>q,order:()=>q,eq:()=>q,range:()=>q,abortSignal:async()=>{if(options.pending)await options.pending;calls.push({table});return {data:options.rows||[],count:0};}};return q;}};
 const window={AIWiseAuth:{snapshot:()=>auth,subscribe:fn=>{subscriber=fn;fn(auth);}},AIWiseBackend:{getClient:async()=>backend},AIWiseAccount:{open:()=>account++},AIWiseMotion:{enter:()=>{}},addEventListener:()=>{},dispatchEvent:()=>{}};
 const location={hash:'#beta',pathname:'/workspace/'};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../page-feedback.js'),'utf8'),{window,document,location,URL,URLSearchParams,Event:dom.Event,crypto:require('node:crypto').webcrypto,AbortController,setTimeout:()=>1,clearTimeout:()=>{}});
 return {document,api:window.AIWisePageFeedback,calls,location,fail:v=>failure=v,account:()=>account,auth:a=>{auth=a;subscriber(a);}};
}
test('signed-out bubble opens account without reading private feedback',async()=>{const f=fixture({signedOut:true});f.api.open();await settle();assert.equal(f.account(),1);assert.equal(f.calls.length,0);});
test('lost send response preserves message and retry UUID; body/page context remain unchanged',async()=>{
 const f=fixture({failure:true});f.api.open();f.document.querySelector('#pf-body').value='Please improve the list.';const submit=()=>f.document.querySelector('form').onsubmit({preventDefault(){},currentTarget:f.document.querySelector('form')});await submit();assert.equal(f.document.querySelector('#pf-body').value,'Please improve the list.');const first=f.calls.find(c=>c.name==='workspace_send_page_feedback');assert.equal(first.args.p_page,'workspace/#beta');assert(!('author_id' in first.args));
 f.location.hash='#common';f.document.querySelector('[data-pf-close]').click();f.api.open();f.fail(false);await submit();const sends=f.calls.filter(c=>c.name==='workspace_send_page_feedback');assert.equal(sends[1].args.p_id,first.args.p_id);assert.equal(sends[1].args.p_page,first.args.p_page);assert.equal(f.document.querySelector('#pf-body').value,'');assert.match(f.document.querySelector('[data-pf-send-status]').textContent,/Sent/);
});
test('members see replies as text but no administrator response forms; unsafe page links are rejected',async()=>{
 const f=fixture({rows:[{id:'x',author_name:'<img>',kind:'bug',page:'javascript:alert(1)',page_title:'<svg>',body:'<script>secret</script>',status:'reviewing',response:'<img src=x>',administrator_name:'Admin',created_at:'2026-10-01'}]});f.api.open('inbox');await settle();assert.equal(f.document.querySelectorAll('.pf-message form').length,0);assert.equal(f.document.querySelector('.pf-message img'),null);assert.match(f.document.querySelector('.pf-message').textContent,/<script>secret/);assert.equal(f.document.querySelector('[data-pf-source]').getAttribute('href'),'https://example.test/workspace/');
});
test('revocation clears private dialog and prevents late inbox content from reappearing',async()=>{let finish;const pending=new Promise(r=>finish=r);const f=fixture({pending,rows:[{body:'Private message'}]});f.api.open('inbox');await settle();f.auth({status:'not-member',user:{id:'one'}});finish();await settle();assert.equal(f.document.querySelector('.pf-dialog').textContent,'');});
test('administrator response sends optimistic revision with no client identity override',async()=>{const f=fixture({role:'admin',rows:[{id:'x',author_name:'Reviewer',page:'workspace/#beta',page_title:'Beta',kind:'idea',body:'An idea',status:'new',response:'',revision:4,created_at:'2026-10-01'}]});f.api.open('inbox');await settle();const form=f.document.querySelector('.pf-message form');form.querySelector('textarea').value='We are checking this.';form.querySelector('select').value='reviewing';await form.onsubmit({preventDefault(){}});const update=f.calls.find(c=>c.name==='workspace_update_page_feedback');assert.equal(update.args.p_revision,4);assert.equal(update.args.p_response,'We are checking this.');assert.equal(update.args.p_status,'reviewing');});
