const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom');
const source=fs.readFileSync(path.join(__dirname,'../published-release.js'),'utf8'),settle=()=>new Promise(r=>setTimeout(r,0));
const version={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',number:4,title:'Review <one>'};
function fixture(options={}){
 const dom=parseHTML('<html><body><main id="room"></main></body></html>'),{document}=dom;Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._value||this.querySelector('option')?.value;},set(v){this._value=v;}});let state={status:'member',role:options.role||'admin',user:{id:'owner'}},calls=[],rows=options.rows||[],finish;
 const pending=options.pending?new Promise(r=>finish=r):Promise.resolve();
 const client={from:name=>{calls.push(name);const chain={select:()=>chain,eq:()=>chain,order:()=>chain,limit:()=>chain,abortSignal:async()=>{await pending;return {data:name==='workspace_releases'?rows:options.empty?[]:[version],error:options.error};}};return chain;},rpc:(name,body)=>{calls.push({name,body});return {abortSignal:async()=>({data:name==='workspace_beta_review_context'?{fingerprint:options.oldSetup?null:'current-copy',changes:[],checks:[],open_memos:0}:options.enabled!==false,error:options.error})};},functions:{invoke:async(name,{body})=>{calls.push({name,body});if(options.onInvoke)options.onInvoke(body,rows);return options.invokeResult||{data:{ok:true}};}}};
 const window={AIWiseBetaChecklist:{progress:()=>({total:0,reviewed:0,open:0})},AIWiseAuth:{snapshot:()=>state},AIWiseBackend:{getClient:async()=>client}};
 vm.runInNewContext(source,{window,document,crypto:require('node:crypto').webcrypto,AbortController,setTimeout:()=>1,clearTimeout:()=>{}});
 const dispose=window.AIWisePublishedRelease.render((area,title,help,body)=>document.querySelector('#room').innerHTML=body,options.renderOptions||{});
 return{document,calls,dispose,finish,setAuth:s=>state=s};
}
test('an empty archive can prepare the first publication without creating a snapshot first',async()=>{const f=fixture({empty:true});await settle();assert.equal(f.document.querySelector('[data-prepare]').disabled,false);assert.match(f.document.body.textContent,/Review before publishing/);assert(!f.calls.includes('workspace_beta_versions'));f.dispose();});
test('prepared releases require a distinct Publish action, and deployment claims match status',async()=>{
 const f=fixture({rows:[{...version,id:version.id,version_id:version.id,version_number:4,version_title:'Safe <title>',candidate_fingerprint:'current-copy',status:'prepared',created_at:'2026-10-01'},{...version,id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',version_id:version.id,version_number:4,version_title:'Previous',status:'committed',deployment_status:'building',created_at:'2026-10-01'}]});await settle();
 assert.equal(f.document.querySelectorAll('[data-approve]').length,0);assert.match(f.document.body.textContent,/Updating the student website/);assert.doesNotMatch(f.document.body.textContent,/Deployed to students/);assert.equal(f.document.querySelector('title'),null);assert.equal(f.calls.some(c=>c.name==='workspace_approve_release'),false);f.dispose();
});
test('prepare sends the reviewed current fingerprint and stable request ID, never publishes',async()=>{const f=fixture();await settle();await f.document.querySelector('[data-prepare]').onclick();const invoke=f.calls.find(c=>c.name==='aiwise-release');assert.equal(invoke.body.operation,'prepare');assert.equal(invoke.body.version_id,undefined);assert.equal(invoke.body.fingerprint,'current-copy');assert.equal(f.calls.some(c=>c.name==='workspace_approve_release'),false);f.dispose();});
test('members cannot query release data',async()=>{const f=fixture({role:'member'});await settle();assert.equal(f.calls.length,0);f.dispose();});
test('missing setup disables publication without claiming failure of the student site',async()=>{const f=fixture({error:{code:'PGRST202'}});await settle();assert.match(f.document.body.textContent,/setup is not ready/);assert.equal(f.document.querySelector('[data-prepare]').disabled,true);f.dispose();});
test('late data cannot appear after account change',async()=>{const f=fixture({pending:true});await settle();f.setAuth({status:'signed-out'});f.finish();await settle();assert.equal(f.document.querySelector('[data-release-root]').textContent,'');f.dispose();});

test('stale preparation is replaced by the review-publication action',async()=>{const f=fixture({renderOptions:{fromBeta:true},rows:[{id:version.id,version_id:null,candidate_fingerprint:'older-copy',status:'prepared',created_at:'2026-10-01'}]});await settle();assert.equal(f.document.querySelector('[data-approve]'),null);assert.equal(f.document.querySelector('[data-prepare]').hidden,false);assert.equal(f.document.querySelector('#release-version'),null);f.dispose();});
test('missing cycle migration blocks preparing against the old saved-version contract',async()=>{const f=fixture({oldSetup:true});await settle();assert.equal(f.document.querySelector('[data-prepare]').disabled,true);assert.match(f.document.body.textContent,/setup is not ready/);f.dispose();});

for(const [code,pattern] of [['github_secrets_missing',/AIWISE_GITHUB_CLIENT_ID and AIWISE_GITHUB_PRIVATE_KEY/],['invalid_private_key',/complete RSA PEM/],['database_unavailable',/database request/]])test(`preparation explains ${code} and keeps it visible through status refresh`,async()=>{const f=fixture({invokeResult:{error:{context:{json:async()=>({code})}}}});await settle();await f.document.querySelector('[data-prepare]').onclick();assert.match(f.document.querySelector('[data-release-message]').textContent,pattern);f.document.querySelector('[data-refresh]').onclick();await settle();assert.match(f.document.querySelector('[data-release-message]').textContent,pattern);assert.equal(f.calls.some(c=>c.name==='workspace_approve_release'),false);f.dispose();});
test('unknown preparation errors never display upstream content',async()=>{const f=fixture({invokeResult:{error:{context:{json:async()=>({code:'<secret upstream body>',message:'private key'})}}}});await settle();await f.document.querySelector('[data-prepare]').onclick();assert.match(f.document.querySelector('[data-release-message]').textContent,/could not be confirmed/);assert.doesNotMatch(f.document.body.textContent,/secret upstream body|private key/);f.dispose();});

test('duplicate prepared copies produce one current approval and no publication-history entries',async()=>{const r={id:version.id,status:'prepared',candidate_fingerprint:'current-copy',created_at:'2026-10-01'};const f=fixture({rows:[r,{...r,id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'}]});await settle();assert.equal(f.document.querySelectorAll('[data-approve]').length,1);assert.equal(f.document.querySelector('[data-approve]').dataset.approve,r.id);assert.equal(f.document.querySelector('[data-prepare]').hidden,true);assert.match(f.document.querySelector('[data-history-count]').textContent,/0/);assert.equal(f.document.querySelector('.release-history').hasAttribute('open'),false);f.dispose();});
test('failed publication remains visible after its content becomes the next comparison baseline',async()=>{const f=fixture({rows:[{id:version.id,version_id:version.id,version_number:2,version_title:'2026-10-01',status:'failed',candidate_fingerprint:'earlier-copy',error_code:'github_unavailable'}]});await settle();assert.match(f.document.querySelector('[data-state-title]').textContent,/needs attention/);assert.equal(f.document.querySelectorAll('[data-retry]').length,1);assert.equal(f.document.querySelector('[data-prepare]').hidden,true);f.dispose();});

test('a lost preparation response is reconciled with its saved copy instead of leaving a false error',async()=>{const f=fixture({invokeResult:{error:{context:{json:async()=>({})}}},onInvoke:(body,rows)=>rows.push({id:body.id,status:'prepared',candidate_fingerprint:body.fingerprint})});await settle();await f.document.querySelector('[data-prepare]').onclick();assert.equal(f.document.querySelector('[data-release-message]').textContent,'');assert.equal(f.document.querySelectorAll('[data-approve]').length,1);assert.equal(f.document.querySelector('[data-prepare]').hidden,true);f.dispose();});
