const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const {parseHTML}=require(process.env.LINKEDOM_MODULE||'linkedom'),settle=()=>new Promise(r=>setTimeout(r,0));
const script=fs.readFileSync(path.join(__dirname,'../team-invitations.js'),'utf8');
function fixture(options={}){const {document,window:dom}=parseHTML('<html><body><div id="host"></div></body></html>');document.currentScript={src:'https://example.test/workspace/team-invitations.js'};dom.HTMLElement.prototype.showModal=function(){this.open=true};dom.HTMLElement.prototype.close=function(){this.open=false};Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._value||this.querySelector('option[selected]')?.value||this.querySelector('option')?.value},set(v){this._value=v}});
let state={status:'member',role:options.role||'admin',user:{id:'admin'}},fail=options.failCreate,calls=[],rows=options.rows||[],clipboard=[];
const backend={rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>{if(name==='workspace_create_invitation'){if(fail){fail=false;return {error:{code:'network'}};}rows.push({id:args.p_id,label:args.p_label,role:args.p_role,eligibility:args.p_eligibility,target:args.p_target,status:'active',uses:0,max_uses:args.p_max_uses,expires_at:'2026-10-08T00:00:00Z'});return {data:args.p_id};}if(name==='workspace_revoke_invitation'){rows.find(r=>r.id===args.p_id).status='revoked';return {data:null};}return {data:{invitations:rows,total:rows.length}};}};}};
const window={AIWiseAuth:{snapshot:()=>state},AIWiseBackend:{getClient:async()=>backend}};vm.runInNewContext(script,{window,document,URL,AbortController,setTimeout,clearTimeout,crypto:webcrypto,Uint8Array,navigator:{clipboard:{writeText:async value=>clipboard.push(value)}}});const api=window.AIWiseInvites.mount(document.querySelector('#host'));return{document,api,calls,clipboard,setAuth:s=>state=s};}
test('administrator invite enforces named recipient and one use in the form',async()=>{const f=fixture();await settle();f.document.querySelector('[data-invite-create]').click();const role=f.document.querySelector('#invite-role');role.value='admin';role.onchange();assert.equal(f.document.querySelector('#invite-eligibility').value,'email');assert(f.document.querySelector('#invite-eligibility').disabled);assert.equal(f.document.querySelector('#invite-limit').value,'1');assert(f.document.querySelector('#invite-limit').disabled);assert.equal(f.api.canLeave(),false);f.api.dispose();});
test('uncertain creation retries with the same secret and request ID; only the completed link can be copied',async()=>{const f=fixture({failCreate:true});await settle();f.document.querySelector('[data-invite-create]').click();f.document.querySelector('#invite-label').value='Review <team>';f.document.querySelector('#invite-target').value='Member@EUR.nl';const form=f.document.querySelector('dialog form');await form.onsubmit({preventDefault(){}});await form.onsubmit({preventDefault(){}});const calls=f.calls.filter(c=>c.name==='workspace_create_invitation');assert.equal(calls.length,2);assert.deepEqual(calls[0].args,calls[1].args);assert.match(calls[0].args.p_token,/^[a-f0-9]{64}$/);assert.equal(calls[0].args.p_target,'member@eur.nl');const link=f.document.querySelector('#invite-created-url').value;assert.match(link,/^https:\/\/example.test\/workspace\/invite.html#[a-f0-9-]+\.[a-f0-9]{64}$/);await f.document.querySelector('[data-copy]').onclick();assert.equal(f.clipboard[0],link);assert.equal(f.document.querySelector('team'),null);f.api.dispose();assert.equal(f.document.querySelector('dialog'),null);});
test('revocation needs its explicit action and leaves a visible revoked record',async()=>{const row={id:'one',label:'Reviewers',role:'member',eligibility:'domain',target:'eur.nl',status:'active',max_uses:5,uses:1,expires_at:'2026-10-08'};const f=fixture({rows:[row]});await settle();f.document.querySelector('[data-revoke]').click();assert.equal(f.calls.some(c=>c.name==='workspace_revoke_invitation'),false);await f.document.querySelector('[data-confirm]').onclick();assert.equal(f.calls.find(c=>c.name==='workspace_revoke_invitation').args.p_id,'one');assert.match(f.document.body.textContent,/Revoked/);f.api.dispose();});
test('ordinary members never read invitation management or create a link',async()=>{const f=fixture({role:'member'});await settle();f.document.querySelector('[data-invite-create]').click();assert.equal(f.calls.length,0);assert.equal(f.document.querySelector('dialog'),null);f.api.dispose();});
