/* Guides describe implemented behavior; local-only and unconnected areas are explicit. */
(() => {
 const card=(title,body,steps)=>({title,body,steps});
 const guides={
  login:{name:'Signing in',cards:[card('Welcome to AI-Wise WorkSpace','Sign in with your team account to start.', ['Choose Sign in or create account.','Use your email and password.']),card('Joining the team','Creating an account and receiving team access are separate steps.',['Create your account and confirm the email.','An administrator then approves your access.','Reopen the account window to refresh your status.']),card('Help is always nearby','The ⓘ button opens the guide for the page you are using.',['Use Next, Back or swipe to move between cards.','You can skip a guide and reopen it later.'])]},
  welcome:{name:'Welcome to your workspace',cards:[card('Your team workspace','Move from course context to content, team review and a student release.',['Use the left sidebar or campus map to navigate.','Collapse the sidebar when you need more editing space.']),card('Two studios, one module','Common Studio and Content Studio use the same editing workflow.',['Common Studio: shared chapters, navigation text and the system map.','Content Studio: examples specific to AWS I, PED or Others.','Choose English or Nederlands before editing.']),card('Draft → review → students','Each step has a separate purpose.',['Save a draft, then submit it for a Control Tower decision.','Review accumulated approved changes in Beta.','Review the publication copy, then confirm Publish to students.']),card('Your work and your team','Open My page from the right edge whenever you need it.',['Find mentions, page feedback and recent pages.', 'Use the Feedback bubble on any page; messages go to the administrator inbox.','Keep personal notes or dated calendar memos on this browser.','Use ⓘ on any page to revisit its guide.'])]},
  'welcome-member':{name:'Welcome to AI-Wise Beta',cards:[card('Your review space','Your account can preview Beta and share feedback.',['Open AI-Wise Beta.','Open the next release or an earlier published version.']),card('Point to the change','Give feedback directly on the module.',['Choose Add memo, then a comment, highlight or box tool.','Select the relevant content and explain your suggestion.','Reply or mention a teammate with @.']),card('Stay in the conversation','My page is always available from the right edge.',['Find mentions and your recent feedback.', 'Use the Feedback bubble to report Workspace errors or suggest improvements.','Save personal notes on this browser.','Use ⓘ whenever you need the guide again.'])]},
  home:{name:'Workspace home',cards:[card('Choose your next task','The map and list show the same Workspace destinations.',['Use Course Profiler for teaching context.','Use the studios for module content.','Use Beta for review and Control Tower for decisions.']),card('Find recent activity','The home activity popup links back to the relevant request or editor.',['Choose View all to browse tips and recorded activity.','Use My page for your own mentions and recent pages.']),card('Shared resources','The sidebar keeps team links and account tools together.',['Open the shared drive and team GitHub from Resources.','Use Account for your profile and administrator team management.'])]},
  common:{name:'Common Studio',cards:[card('Content shared across courses','Common Studio covers the shared AI Orientation content.',['Choose C1, C2, C3 or the system map.','Open an item to edit it beside its preview.']),card('Keep languages separate','English and Nederlands have separate editing spaces.',['Choose the language before you start.','Course-specific examples belong in Content Studio.','Saving a draft does not publish it.'])]},
  studio:{name:'Content Studio',cards:[card('Choose the course first','Course examples give the shared module its teaching context.',['Open AWS I, PED or Others.','Choose an item from C2 or C3.','New course registrations need their content connection before editing.']),card('Edit alongside the preview','The same tools are available in both studios.',['Choose English or Nederlands.','Click a marked item or use the item list.','Save your draft before submitting for review.'])]},
  editor:{name:'Studio editor',cards:[card('Find the right item','The item list groups content by chapter.',['Choose your language.','Open the item list or use the previous and next arrows.','Click an outlined preview item to edit it.']),card('Check the result as you write','The preview follows your current edits.',['Edit the fields in the right panel.','Drag the panel edge if you need more room.','Check longer text in the preview before saving.']),card('Save, then submit','A saved draft remains on this browser until you submit it.',['Save draft keeps your current work.','Send to Control Tower sends a saved copy to the team.','Control Tower approval updates Beta; a separate Publish approval updates the student site.'])]},
  beta:{name:'Beta & publication history',cards:[card('Choose what to review','Approved Studio changes accumulate in one next-release copy.',['Open preview to start at the first change needing review.','Publish creates a numbered version with its creation date.','Earlier versions are available in the collapsed version list.']),card('Keep feedback with its version','Publishing freezes the approved content, checks and feedback.',['Use the version name to confirm your review target.','Mark each checked item as reviewed; the team sees your progress.', 'Administrators prepare the next release, then confirm Publish. Later approvals start accumulating again.'])]},
  'beta-preview':{name:'Beta preview & feedback',cards:[card('Start with the changes','The preview opens at the first item needing review.',['Use Changes to review in the right panel to inspect and mark each change.','Next change moves to the next item needing review.','Use the top bar to change page, course or language.','Review versions returns to the version list.']),card('Mark what you mean','Choose Add memo to reveal the feedback tools.',['Comment: select a tagged content box.','Highlight: mark the text you want to discuss.','Box: draw around an area of the preview.', 'Pin: point to a specific spot.','Use Content box to choose a location with the keyboard.']),card('Keep the conversation together','Write the suggestion, then post your comment.',['Use @ to mention a teammate.','Reply within the same thread.','Filter Open, Resolved or All; administrators can resolve feedback.']),card('Compare changes','Changes & history sits below the feedback list.',['Saved-version changes are marked in the preview.','Select an item to inspect earlier content and related feedback.', 'Use Mark reviewed beside the item or in Changes to review.','Current approved Beta explains when a saved-version comparison is unavailable.'])]},
  tower:{name:'Control Tower',cards:[card('Follow the content route','Open a route on the map or switch to the list.',['Common and Content Studio submissions go to Beta.','Open a request to inspect its submitted copy.','Keep revision reasons with the request.']),card('Approval and publishing are separate','An administrator records the decision on a shared Studio submission.',['Approving updates Beta and queues its GitHub commit.','Commit and deployment status appear separately.','Beta → Published opens the final publication flow.']),card('Check the request type','Some older request routes still use local records.',['Shared Studio submissions are team records.','Local profile and prototype request records stay on this browser.','Read the status shown on the request before treating it as transferred.'])]},
  release:{name:'Publish to students',cards:[card('Start with the next release','Approved Studio changes accumulate until Publish.',['Finish reviewing the next release in Beta.','Choose Review publication to check the content before publishing.','Reviewing the publication copy does not change the student website.']),card('Approve the student release','Final Publish creates the numbered, dated version.',['Confirm the reviewed content. New approvals require preparing again.','The queued worker creates the GitHub commit.','Follow the GitHub update and website deployment steps. Only Live on the student site confirms completion.']),card('If publishing stops','The status explains what needs attention.',['If the student site changed, prepare a new release.','Retry a failed commit only after checking the connection.','Open deployment details for a Pages failure.'])]},
  courses:{name:'Courses',cards:[card('Register course information','Courses keeps the names and identifiers used in Workspace.',['Add a course or open its details.','Use its map or list to find connected materials.']),card('Know what is connected','Registration alone does not create module content.',['Course registrations currently stay on this browser.','Existing connected courses can open Content Studio.','Areas that need setup are labelled.'])]},
  manager:{name:'Course Profiler Manager',cards:[card('Review the teaching context','Use this space to inspect course materials and existing prompts.',['Open Course Profiler for the teacher’s course description.','Inspect Current prompts and Current activities.']),card('Availability is shown on each area','Profile intake and package assembly are not connected yet.',['Prompt inspection is read-only.','Activity configuration is not an editor yet.','Do not treat a local profile as a shared team submission.'])]},
  profiler:{name:'Course Profiler',cards:[card('Describe your course','Start with course context, goals and how the weeks are organised.',['Use Sample to explore a populated example.','Use New when you want to begin a separate profile.']),card('Break work into tasks','Describe what students do and what support they receive.',['Add tasks and choose their shape.','Complete the task details and learning actions.','Use the unfinished count to find what remains.']),card('Keep a copy','Profiles currently save on this browser.',['Export JSON to keep a copy you can import later.','Export MD for a readable course description.','Shared profile intake is not connected yet.'])]},
  team:{name:'Team management',cards:[card('Invite a teammate','Share one link, then review the join requests in Team management.',['Anyone with the link can request to join after confirming their email.','Links last 7 days and have no limit on people.','Review a request, confirm membership and choose access. Member is the default.','Change permissions later with Manage access. Revoke a link to stop new requests.']),card('Manage access from Workspace','Administrators can review accounts and grant team access.',['Find the person in the list.','Open Manage access and check their email.','Choose their role and whether access is active.']),card('Choose the right role','Members review Beta; administrators also manage content and decisions.',['Member: preview and feedback.','Administrator: studios, approvals, releases and team access.','Keep at least one active administrator.'])]},
  records:{name:'Records Office',cards:[card('This area is not connected yet','Records Office is a placeholder for a broader history view.',['Use saved Beta versions for review snapshots.','Use request history for Studio decisions.','Use release records for student publication status.'])]},
  'my-page':{name:'My page',cards:[card('Your personal workspace','This panel stays available from the right edge.',['Notifications shows mentions from teammates. Page feedback opens your messages and administrator replies.','Recent pages helps you return to where you worked.','My work brings together your feedback and available contributions.']),card('Notes and dates','Keep a thought or a memo for a particular day.',['Choose a date and enter its memo.','Use Save notes to keep changes.','Personal notes and recent pages stay on this browser under your account.'])]},
  account:{name:'Your account',cards:[card('Your team identity','Your display name appears with your feedback.',['Update your display name in Account settings.','Check which email you are signed in with.','Sign out when you finish on a shared computer.'])]}
 };
 guides['common-editor']={...guides.editor,name:'Common Studio editor'};guides['studio-editor']={...guides.editor,name:'Content Studio editor'};
 window.AIWiseTutorialContent=Object.freeze({guides,card});
})();
